### ISSUE TITLE
Cannot create new documents

### ISSUE THREAD

**Issue by Sabinno** [cvfosammmm/Lemma#1]
Pretty simple. Downloaded Lemma from the Pop Shop on unmodified Pop OS 22.04. I can start the document creation flow but can't proceed even with a title filled in.

![image](https://github.com/cvfosammmm/Lemma/assets/6600505/fe2c52df-50c9-4477-be48-e69c9df27898)

**Comment by cvfosammmm** [comment]
Thanks for reporting this. A new release with the fix will be available in a couple of hours.
