### ISSUE TITLE
Left bar color

### ISSUE THREAD

**Issue by alcir** [cvfosammmm/Lemma#2]
Hello, interesting project.

I installed Lemma from Flathub.
The left bar is green, while in the screenshots it is gray.
Is this intended or?

**Comment by cvfosammmm** [comment]
I made it green on purpose, but there will be more changes to the colors soon.

If you don't like the default colors btw.: this is just a theme and can be easily changed. This should be exposed in the UI as well, once I or someone else gets around to it..
