### ISSUE TITLE
Add synchronization with Dav or NextCloud

### ISSUE THREAD

**Issue by Froggy232** [cvfosammmm/Lemma#3]
Hi,
Thanks for your app, it looks wonderfull!
Would you plan to add sync feature with Dav server (like Baïkal), or NextCloud Note in the future?
This way, it would be possible to sync notes between devices.
I think Dav would be a better option, but maybe I'm wrong as I'm not developper.
Are you open to this idea, or do you prefeer your app to stay offline?
Thanks you!

**Comment by cvfosammmm** [comment]
Thanks for asking. I haven't really thought about syncing. I wouldn't rule it out for sure, but I would want the app to mature a lot more before making plans in this direction. So I'm closing this for now as it's not really on the cards just yet.

**Comment by aleksrutins** [comment]
A simple way to allow people to do this on their own, for starters, might be to allow changing the note storage location.
