### ISSUE TITLE
 This application can not open files

### ISSUE THREAD

**Issue by fastrizwaan** [cvfosammmm/Lemma#6]
```
$ flatpak run org.cvfosammmm.Lemma  ~/Document.md

(lemma:2): GLib-GIO-CRITICAL **: 06:46:20.268: This application can not open files.
```

hi we can use `on_open` method to give file argument to our python gtk4 app. Also you can use a socket server to start lemma or load cli files to existing instance of lemma.

https://github.com/fastrizwaan/WineCharm/blob/6a150e882421e458435313f88b8ad2999f9b065c/winecharm.py#L57

https://github.com/fastrizwaan/WineCharm/blob/6a150e882421e458435313f88b8ad2999f9b065c/winecharm.py#L1939

you can take the help of chatgpt 4o and codestral ai https://chat.mistral.ai/chat.

**Comment by cvfosammmm** [comment]
Hi, Lemma isn't really supposed to work on files in this sense, but _documents_. Those can be imported from the filesystem, but not opened. So I don't think it makes sense to add this method.
